beez/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from api import views

app_name = 'api'

router = routers.SimpleRouter(trailing_slash=False)
router.register(r'apiaries', views.ApiaryViewSet, base_name='apiary')
router.register(r'hives', views.HiveViewSet, base_name='hive')
router.register(r'inspections', views.InspectionViewSet, base_name='inspection')
router.register(r'harvests', views.HarvestViewSet, base_name='harvest')

schema_view = get_schema_view(
   openapi.Info(
      title="Beez API",
      default_version='v1',
      description="Swagger/OpenAPI definition for Beez",
      license=openapi.License(name="GNU GPLv3"),
   ),
   public=True,
)

urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=None), name='schema-json'),

    path('settings', views.UpdateSettingsView.as_view()),

    path('auth', obtain_jwt_token),
    path('auth/refresh', refresh_jwt_token),

    path('search', views.SearchView.as_view()),

    path('', include(router.urls)),
]

beez/frontend/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from frontend.views import apiary, hive, user, inspection, statistics, settings, search

app_name = 'frontend'

urlpatterns = [
    path('', TemplateView.as_view(template_name='frontend/index.html'), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', user.RegisterView.as_view(), name='register'),
    path('search', search.search, name='search'),

    path('dashboard/apiaries', apiary.ApiaryListView.as_view(), name='apiary-list'),
    path('dashboard/apiaries/create-apiary', apiary.ApiaryCreateView.as_view(), name='apiary-create'),
    path('dashboard/apiaries/<int:pk>', apiary.ApiaryDetailView.as_view(), name='apiary-detail'),
    path('dashboard/apiaries/<int:pk>/edit', apiary.ApiaryUpdateView.as_view(), name='apiary-edit'),
    path('dashboard/apiaries/<int:pk>/add-file', apiary.ApiaryFileView.as_view(), name='apiary-add-file'),
    path('dashboard/apiaries/<int:pk>/create-hive', hive.HiveCreateView.as_view(), name='hive-create'),
    path('dashboard/apiaries/files/<int:pk>', apiary.ApiaryFileDownloadView.as_view(), name='apiary-file'),
    path('dashboard/apiaries/files/<int:pk>/delete', apiary.ApiaryFileDeleteView.as_view(), name='apiary-file-delete'),

    path('dashboard/hives/<int:pk>', hive.HiveDetailView.as_view(), name='hive-detail'),
    path('dashboard/hives/<int:pk>/edit', hive.HiveUpdateView.as_view(), name='hive-edit'),
    path('dashboard/hives/<int:pk>/add-file', hive.HiveFileView.as_view(), name='hive-add-file'),
    path('dashboard/hives/<int:pk>/transfer', hive.HiveTransferView.as_view(), name='hive-transfer'),
    path('dashboard/hives/<int:pk>/delete', hive.HiveDeleteView.as_view(), name='hive-delete'),
    path('dashboard/hives/<int:pk>/delete', lambda x: None, name='hive-delete'),
    path('dashboard/hives/<int:pk>/create-inspection', inspection.InspectionCreateView.as_view(), name='inspection-create'),
    path('dashboard/hives/files/<int:pk>', hive.HiveFileDownloadView.as_view(), name='hive-file'),
    path('dashboard/hives/files/<int:pk>/delete', hive.HiveFileDeleteView.as_view(), name='hive-file-delete'),
    path('dashboard/hives/<int:pk>/edit-queen', hive.QueenEditView.as_view(), name='hive-edit-queen'),
    path('dashboard/hives/<int:pk>/add-queen', hive.QueenCreateView.as_view(), name='hive-add-queen'),
    path('dashboard/hives/<int:pk>/delete-queen', hive.QueenDeleteView.as_view(), name='hive-delete-queen'),

    path('dashboard/inspections/<int:pk>', inspection.InspectionDetailView.as_view(), name='inspection-detail'),
    path('dashboard/inspections/<int:pk>/edit', inspection.InspectionUpdateView.as_view(), name='inspection-edit'),
    path('dashboard/inspections/<int:pk>/delete', inspection.InspectionDeleteView.as_view(), name='inspection-delete'),

    path('dashboard/statistics/overview', statistics.StatisticsView.as_view(), name='statistics'),
    path('dashboard/statistics/hive/<int:pk>', statistics.HiveStatisticsView.as_view(), name='statistics-hive'),
    path('dashboard/settings', settings.SettingsView.as_view(), name='settings'),
]

beez/frontend/views/apiary.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from private_storage.views import PrivateStorageDetailView

from core.models import Apiary, Hive, File
from frontend import weather


class ApiaryListView(LoginRequiredMixin, ListView):
    template_name = 'frontend/apiary/list.html'
    context_object_name = 'apiaries'

    def get_queryset(self):
        return self.request.user.apiaries.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_hives'] = Hive.objects.filter(apiary__owner=self.request.user).count()

        return context


class ApiaryDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/apiary/detail.html'
    context_object_name = 'apiary'

    def get_queryset(self):
        return self.request.user.apiaries.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        apiary = context.get('apiary')
        context['weather'] = weather.get_daily_forecast(
            latitude=apiary.latitude,
            longitude=apiary.longitude,
            units=self.request.user.settings.temperature_unit,
        )

        return context


class ApiaryCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/apiary/form.html'
    model = Apiary
    fields = ['name', 'latitude', 'longitude', 'address', 'radius', 'notes']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApiaryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/apiary/form.html'
    model = Apiary
    fields = ['name', 'latitude', 'longitude', 'address', 'radius', 'notes']

    def get_queryset(self):
        return self.request.user.apiaries.all()


class ApiaryFileView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/apiary/file_form.html'
    model = File
    fields = ['file']

    def get_success_url(self):
        return reverse('frontend:apiary-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.apiary = get_object_or_404(Apiary, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class ApiaryFileDownloadView(LoginRequiredMixin, PrivateStorageDetailView):
    model = File
    model_file_field = 'file'
    content_disposition = True

    def get_queryset(self):
        return super().get_queryset().filter(apiary__isnull=False, apiary__owner=self.request.user)


class ApiaryFileDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/apiary/file_delete.html'
    model = File
    context_object_name = 'file'

    def get_queryset(self):
        return File.objects.filter(apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.apiary.get_absolute_url()

beez/frontend/views/hive.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from private_storage.views import PrivateStorageDetailView

from core.models import Hive, Apiary, File, Queen


class HiveDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/hive/detail.html'
    context_object_name = 'hive'

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)


class HiveCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/form.html'
    model = Hive
    fields = ['name', 'notes', 'makes_honey']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apiary'] = get_object_or_404(Apiary, pk=self.kwargs.get('pk'))

        return context

    def form_valid(self, form):
        form.instance.apiary = Apiary.objects.get(owner=self.request.user, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class HiveUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/form.html'
    model = Hive
    fields = ['name', 'notes', 'makes_honey']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apiary'] = self.get_object().apiary

        return context

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)


class HiveTransferView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/transfer.html'
    model = Hive
    fields = ['apiary']

    def _get_available_apiaries(self):
        current_apiary = self.get_object().apiary
        current_user = self.request.user

        return Apiary.objects.filter(owner=current_user).exclude(pk=current_apiary.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['can_transfer'] = self._get_available_apiaries().count() > 0

        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['apiary'].queryset = self._get_available_apiaries()

        return form


class HiveDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/delete.html'
    model = Hive

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)

    def get_success_url(self):
        return self.get_object().apiary.get_absolute_url()


class HiveFileView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/file_form.html'
    model = File
    fields = ['file']

    def get_success_url(self):
        return reverse('frontend:hive-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.hive = get_object_or_404(Hive, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class HiveFileDownloadView(LoginRequiredMixin, PrivateStorageDetailView):
    model = File
    model_file_field = 'file'
    content_disposition = True

    def get_queryset(self):
        return super().get_queryset().filter(hive__isnull=False, hive__owner=self.request.user)


class HiveFileDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/file_delete.html'
    model = File
    context_object_name = 'file'

    def get_queryset(self):
        return File.objects.filter(hive__apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.hive.get_absolute_url()


class QueenEditView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/queen/form.html'
    model = Queen
    fields = ['year', 'number']

    def get_queryset(self):
        return Queen.objects.filter(hive__apiary__owner=self.request.user)

    def get_object(self, queryset=None):
        qs = self.get_queryset() if queryset is None else queryset
        return qs.get(hive__pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = self.get_object().hive

        return context


class QueenCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/queen/form.html'
    model = Queen
    fields = ['year', 'number']

    def get_success_url(self):
        return reverse('frontend:hive-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.hive = get_object_or_404(Hive, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = get_object_or_404(Hive, pk=self.kwargs.get('pk'))

        return context


class QueenDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/queen/delete.html'
    model = Queen
    context_object_name = 'queen'

    def get_queryset(self):
        return Queen.objects.filter(hive__apiary__owner=self.request.user)

    def get_object(self, queryset=None):
        qs = self.get_queryset() if queryset is None else queryset
        return qs.get(hive__pk=self.kwargs['pk'])

    def get_success_url(self):
        return self.object.hive.get_absolute_url()

beez/frontend/views/inspection.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from core.models import Inspection, Hive
from frontend.views import forms


class InspectionDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/inspection/detail.html'
    model = Inspection
    context_object_name = 'inspection'

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)


class InspectionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/inspection/form.html'
    form_class = forms.InspectionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = get_object_or_404(Hive, pk=self.kwargs.get('pk'))

        return context

    def form_valid(self, form):
        form.instance.hive = Hive.objects.get(apiary__owner=self.request.user, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class InspectionUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/inspection/form.html'
    form_class = forms.InspectionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = self.get_object().hive

        return context

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)


class InspectionDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/inspection/delete.html'
    model = Inspection
    context_object_name = 'inspection'

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.hive.get_absolute_url()

beez/frontend/views/search.py
from django.shortcuts import render

from core.models import Apiary, Hive, Queen


def search(request):
    query = request.GET.get('q')

    apiaries = Apiary.search(query)
    hives = Hive.search(query)
    queens = Queen.search(query)

    return render(request, 'frontend/search.html', {
        'apiaries': apiaries,
        'hives': hives,
        'queens': queens,
    })

beez/frontend/views/settings.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

from core.models import Settings


class SettingsView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Settings
    template_name = 'frontend/settings.html'
    fields = ['weight_unit', 'temperature_unit', 'timezone', 'language']
    success_url = reverse_lazy('frontend:settings')
    success_message = _('Settings saved')

    def get_object(self, queryset=None):
        return self.request.user.settings

beez/frontend/views/statistics.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DetailView

from core.models import Apiary, Hive


class StatisticsView(LoginRequiredMixin, TemplateView):
    template_name = 'frontend/statistics/overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        apiaries = Apiary.objects.filter(owner=self.request.user)
        hives = Hive.objects.filter(apiary__owner=self.request.user)
        context['total_apiaries'] = apiaries.count()
        context['total_hives'] = hives.count()
        context['total_weight'] = sum(hive.last_recorded_weight or 0 for hive in hives)

        return context


class HiveStatisticsView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/statistics/hive.html'
    context_object_name = 'hive'

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)

beez/frontend/views/user.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('frontend:apiary-list')

    def form_valid(self, form):
        response =  super().form_valid(form)
        user = self.object
        if user:
            login(self.request, user)
        return response

beez/frontend/templates/frontend/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="notification {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}is-danger{% endif %}{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}is-info{% endif %}{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}is-success{% endif %}{% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}is-warning{% endif %}">
            <button class="delete"></button>
            {{ message }}
        </div>
    {% endfor %}
    <script>
        (function () {
            var $deleteButtons = document.querySelectorAll('.delete');
            for (var i = 0; i < $deleteButtons.length; i++) {
                $deleteButtons[i].addEventListener('click', function (event) {
                    if (event.target.parentNode.classList.contains('notification')) {
                        event.target.parentNode.remove();
                    }
                });
            }
        }());
    </script>
{% endif %}

beez/frontend/templates/frontend/_navbar.html
{% load static i18n %}
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'frontend:index' %}">
            <img src="{% static 'images/logo.svg' %}" alt="Beez Logo">
            <span style="margin-left: 0.5em;">Beez</span>
        </a>

        <div class="navbar-burger" data-target="navbar-menu">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>

    <div class="navbar-menu" id="navbar-menu">
        <div class="navbar-end">
            {% if user.is_authenticated %}
                <div class="navbar-item">
                    <form action="{% url 'frontend:search' %}" method="get">
                        <div class="field">
                            <p class="control has-icons-left">
                                <input type="text" class="input is-rounded" placeholder="{% trans 'Search' %}" name="q">
                                <span class="icon is-left">
                                    <i class="fa fa-search"></i>
                                </span>
                            </p>
                        </div>
                    </form>
                </div>
                {% if user.is_superuser %}
                    <a href="/admin" class="navbar-item">
                        <span class="icon"><i class="fa fa-bug"></i></span>
                        <span>{% trans "Admin" %}</span>
                    </a>
                {% endif %}
                {% if user.is_impersonate %}
                    <a href="/impersonate/stop" class="navbar-item">
                        <span class="icon"><i class="fas fa-user-alt-slash"></i></span>
                    </a>
                {% endif %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <div class="navbar-link">
                        <span class="icon"><i class="fa fa-user"></i></span>
                        <span>{{ request.user.username }}</span>
                    </div>
                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item" href="{% url 'frontend:apiary-list' %}">
                            <span class="icon"><i class="fa fa-tachometer-alt"></i></span>
                            <span>{% trans "Dashboard" %}</span>
                        </a>
                        <a class="navbar-item" href="{% url 'frontend:settings' %}">
                            <span class="icon"><i class="fa fa-wrench"></i></span>
                            <span>{% trans "Settings" %}</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'frontend:logout' %}">
                            <span class="icon"><i class="fa fa-sign-out-alt"></i></span>
                            <span>{% trans "Log out" %}</span>
                        </a>
                    </div>
                </div>
            {% else %}
                <a href="{% url 'frontend:register' %}" class="navbar-item">
                    <span class="icon"><i class="fa fa-hashtag"></i></span>
                    <span>{% trans "Register" %}</span>
                </a>
                <a href="{% url 'frontend:login' %}" class="navbar-item">
                    <span class="icon"><i class="fa fa-sign-in-alt"></i></span>
                    <span>{% trans "Log in" %}</span>
                </a>
            {% endif %}
        </div>
    </div>
</nav>

beez/frontend/templates/frontend/index.html
{% extends 'frontend/master.html' %}

{% load i18n %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">{% trans 'Welcome to Beez!' %}</h1>

            <div class="content">
                <p>{% blocktrans %}<strong>Beez</strong> is an open-source software project that aims to help beekeepers with different tasks.{% endblocktrans %}</p>

                <div class="message is-warning">
                    <div class="message-body">
                        {% blocktrans %}
                        <strong>Beez</strong> is in its <em>alpha stage</em> which means things constantly change. New
                        features are added while others may disappear. Data loss is also a possibility.
                        {% endblocktrans %}
                    </div>
                </div>

                {% url 'api:schema-json' format='.json' as api_url %}
                {% blocktrans %}
                    <h2>Features</h2>
                    <p>
                        <ul>
                            <li>Manage a number of apiaries and hives.</li>
                            <li>Weather forecast for an apiary's location.</li>
                            <li>Show your apiary on a map and track what area your bees can cover.</li>
                            <li>Create inspections for your hives and collect data.</li>
                            <li>Print out QR codes and stick them to your hives for quick access on mobile phones.</li>
                            <li>A browsable, Swagger/OpenAPI documented, RESTful <a href="{{ api_url }}" target="_blank">API</a>.</li>
                        </ul>
                    </p>
                {% endblocktrans %}

                {% blocktrans %}
                    <h2>Possible future features</h2>
                    <p>
                        <ul>
                            <li>Weather alerts.</li>
                            <li>Detailed statistics.</li>
                            <li>Beekeeping related alerts like missed Varroa treatments or harvest reminders.</li>
                            <li>A native phone app.</li>
                        </ul>

                        If you'd like to see a feature, let us know on the project's <a href="https://gitlab.com/Retzudo/beez/issues" target="_blank" rel="noreferrer">GitLab issues page</a>.
                    </p>
                {% endblocktrans %}
            </div>

            <p class="has-text-centered">
                {% if not user.is_authenticated %}
                    {% url 'frontend:login' as login_url %}
                    {% url 'frontend:register' as register_url %}
                    {% blocktrans %}<a href="{{ register_url }}">Create an account</a> or <a href="{{ login_url }}">log in.</a>{% endblocktrans %}
                {% endif %}
            </p>
        </div>
    </section>
{% endblock %}

beez/frontend/templates/frontend/master.html
{% load staticfiles i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Beez{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.9/css/weather-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'misc/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/safari-pinned-tab.svg' %}" color="#ffc40d">
    <meta name="apple-mobile-web-app-title" content="Beez">
    <meta name="application-name" content="Beez">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="theme-color" content="#ffc40d">

    <style>
        a {
            /* Thanks for adding a weird dotted line around all links Firefox. */
            outline: none;
        }
    </style>
    {% block head %}{% endblock %}
</head>
<body>
    {% include 'frontend/_navbar.html' %}
    {% block body %}{% endblock %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Get all "navbar-burger" elements
            var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

            // Check if there are any navbar burgers
            if ($navbarBurgers.length > 0) {
                // Add a click event on each of them
                $navbarBurgers.forEach(function ($el) {
                    $el.addEventListener('click', function () {

                        // Get the target from the "data-target" attribute
                        var target = $el.dataset.target;
                        var $target = document.getElementById(target);

                        // Toggle the class on both the "navbar-burger" and the "navbar-menu"
                        $el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');
                    });
                });
            }
        });
    </script>
    <footer class="footer">
        <div class="container">
            <div class="content has-text-centered">
                {% blocktrans %}
                    Beez <em>v{{ beez_version }}</em>. Licensed under the <a href="https://www.gnu.org/licenses/gpl-3.0.txt" target="_blank" rel="noreferrer">GNU GPLv3</a>.
                    Code on <a href="https://gitlab.com/Retzudo/beez" target="_blank" rel="noreferrer"><span class="icon"><i class="fab fa-gitlab"></i></span><span>GitLab</span></a>.
                {% endblocktrans %}
            </div>
        </div>
    </footer>
    {% block scripts %}{% endblock %}
</body>
</html>

beez/frontend/templates/frontend/search.html
{% extends 'frontend/master.html' %}

{% load i18n %}

{% block body %}
    <section class="section">
        <div class="container content">
            <h1 class="title"><em>{{ apiaries.count }}</em> {% blocktrans count count=apiaries.count %}Apiary found{% plural %}Apiaries found{% endblocktrans %}</h1>
            <ul>
                {% for apiary in apiaries %}
                    <li><a href="{% url 'frontend:apiary-detail' pk=apiary.pk %}">{{ apiary.name }}</a></li>
                {% endfor %}
            </ul>

            <h1 class="title"><em>{{ hives.count }}</em> {% blocktrans count count=hives.count %}Hive found{% plural %}Hives found{% endblocktrans %}</h1>
            <ul>
                {% for hive in hives %}
                    <li><a href="{% url 'frontend:hive-detail' pk=hive.pk %}">{{ hive.name }}</a></li>
                {% endfor %}
            </ul>

            <h1 class="title"><em>{{ queens.count }}</em> {% blocktrans count count=queens.count %}Queen found{% plural %}Queens found{% endblocktrans %}</h1>
            <ul>
                {% for queen in queens %}
                    <li><a href="{% url 'frontend:hive-detail' pk=queen.hive.pk %}">{{ queen.hive.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}