beez/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from api import views

app_name = 'api'

router = routers.SimpleRouter(trailing_slash=False)
router.register(r'apiaries', views.ApiaryViewSet, base_name='apiary')
router.register(r'hives', views.HiveViewSet, base_name='hive')
router.register(r'inspections', views.InspectionViewSet, base_name='inspection')
router.register(r'harvests', views.HarvestViewSet, base_name='harvest')

schema_view = get_schema_view(
   openapi.Info(
      title="Beez API",
      default_version='v1',
      description="Swagger/OpenAPI definition for Beez",
      license=openapi.License(name="GNU GPLv3"),
   ),
   public=True,
)

urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=None), name='schema-json'),

    path('settings', views.UpdateSettingsView.as_view()),

    path('auth', obtain_jwt_token),
    path('auth/refresh', refresh_jwt_token),

    path('search', views.SearchView.as_view()),

    path('', include(router.urls)),
]

beez/frontend/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from frontend.views import apiary, hive, user, inspection, statistics, settings, search

app_name = 'frontend'

urlpatterns = [
    path('', TemplateView.as_view(template_name='frontend/index.html'), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', user.RegisterView.as_view(), name='register'),
    path('search', search.search, name='search'),

    path('dashboard/apiaries', apiary.ApiaryListView.as_view(), name='apiary-list'),
    path('dashboard/apiaries/create-apiary', apiary.ApiaryCreateView.as_view(), name='apiary-create'),
    path('dashboard/apiaries/<int:pk>', apiary.ApiaryDetailView.as_view(), name='apiary-detail'),
    path('dashboard/apiaries/<int:pk>/edit', apiary.ApiaryUpdateView.as_view(), name='apiary-edit'),
    path('dashboard/apiaries/<int:pk>/add-file', apiary.ApiaryFileView.as_view(), name='apiary-add-file'),
    path('dashboard/apiaries/<int:pk>/create-hive', hive.HiveCreateView.as_view(), name='hive-create'),
    path('dashboard/apiaries/files/<int:pk>', apiary.ApiaryFileDownloadView.as_view(), name='apiary-file'),
    path('dashboard/apiaries/files/<int:pk>/delete', apiary.ApiaryFileDeleteView.as_view(), name='apiary-file-delete'),

    path('dashboard/hives/<int:pk>', hive.HiveDetailView.as_view(), name='hive-detail'),
    path('dashboard/hives/<int:pk>/edit', hive.HiveUpdateView.as_view(), name='hive-edit'),
    path('dashboard/hives/<int:pk>/add-file', hive.HiveFileView.as_view(), name='hive-add-file'),
    path('dashboard/hives/<int:pk>/transfer', hive.HiveTransferView.as_view(), name='hive-transfer'),
    path('dashboard/hives/<int:pk>/delete', hive.HiveDeleteView.as_view(), name='hive-delete'),
    path('dashboard/hives/<int:pk>/delete', lambda x: None, name='hive-delete'),
    path('dashboard/hives/<int:pk>/create-inspection', inspection.InspectionCreateView.as_view(), name='inspection-create'),
    path('dashboard/hives/files/<int:pk>', hive.HiveFileDownloadView.as_view(), name='hive-file'),
    path('dashboard/hives/files/<int:pk>/delete', hive.HiveFileDeleteView.as_view(), name='hive-file-delete'),
    path('dashboard/hives/<int:pk>/edit-queen', hive.QueenEditView.as_view(), name='hive-edit-queen'),
    path('dashboard/hives/<int:pk>/add-queen', hive.QueenCreateView.as_view(), name='hive-add-queen'),
    path('dashboard/hives/<int:pk>/delete-queen', hive.QueenDeleteView.as_view(), name='hive-delete-queen'),

    path('dashboard/inspections/<int:pk>', inspection.InspectionDetailView.as_view(), name='inspection-detail'),
    path('dashboard/inspections/<int:pk>/edit', inspection.InspectionUpdateView.as_view(), name='inspection-edit'),
    path('dashboard/inspections/<int:pk>/delete', inspection.InspectionDeleteView.as_view(), name='inspection-delete'),

    path('dashboard/statistics/overview', statistics.StatisticsView.as_view(), name='statistics'),
    path('dashboard/statistics/hive/<int:pk>', statistics.HiveStatisticsView.as_view(), name='statistics-hive'),
    path('dashboard/settings', settings.SettingsView.as_view(), name='settings'),
]

beez/frontend/views/apiary.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from private_storage.views import PrivateStorageDetailView

from core.models import Apiary, Hive, File
from frontend import weather


class ApiaryListView(LoginRequiredMixin, ListView):
    template_name = 'frontend/apiary/list.html'
    context_object_name = 'apiaries'

    def get_queryset(self):
        return self.request.user.apiaries.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_hives'] = Hive.objects.filter(apiary__owner=self.request.user).count()

        return context


class ApiaryDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/apiary/detail.html'
    context_object_name = 'apiary'

    def get_queryset(self):
        return self.request.user.apiaries.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        apiary = context.get('apiary')
        context['weather'] = weather.get_daily_forecast(
            latitude=apiary.latitude,
            longitude=apiary.longitude,
            units=self.request.user.settings.temperature_unit,
        )

        return context


class ApiaryCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/apiary/form.html'
    model = Apiary
    fields = ['name', 'latitude', 'longitude', 'address', 'radius', 'notes']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApiaryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/apiary/form.html'
    model = Apiary
    fields = ['name', 'latitude', 'longitude', 'address', 'radius', 'notes']

    def get_queryset(self):
        return self.request.user.apiaries.all()


class ApiaryFileView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/apiary/file_form.html'
    model = File
    fields = ['file']

    def get_success_url(self):
        return reverse('frontend:apiary-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.apiary = get_object_or_404(Apiary, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class ApiaryFileDownloadView(LoginRequiredMixin, PrivateStorageDetailView):
    model = File
    model_file_field = 'file'
    content_disposition = True

    def get_queryset(self):
        return super().get_queryset().filter(apiary__isnull=False, apiary__owner=self.request.user)


class ApiaryFileDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/apiary/file_delete.html'
    model = File
    context_object_name = 'file'

    def get_queryset(self):
        return File.objects.filter(apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.apiary.get_absolute_url()

beez/frontend/views/hive.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from private_storage.views import PrivateStorageDetailView

from core.models import Hive, Apiary, File, Queen


class HiveDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/hive/detail.html'
    context_object_name = 'hive'

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)


class HiveCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/form.html'
    model = Hive
    fields = ['name', 'notes', 'makes_honey']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apiary'] = get_object_or_404(Apiary, pk=self.kwargs.get('pk'))

        return context

    def form_valid(self, form):
        form.instance.apiary = Apiary.objects.get(owner=self.request.user, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class HiveUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/form.html'
    model = Hive
    fields = ['name', 'notes', 'makes_honey']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apiary'] = self.get_object().apiary

        return context

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)


class HiveTransferView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/transfer.html'
    model = Hive
    fields = ['apiary']

    def _get_available_apiaries(self):
        current_apiary = self.get_object().apiary
        current_user = self.request.user

        return Apiary.objects.filter(owner=current_user).exclude(pk=current_apiary.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['can_transfer'] = self._get_available_apiaries().count() > 0

        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['apiary'].queryset = self._get_available_apiaries()

        return form


class HiveDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/delete.html'
    model = Hive

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)

    def get_success_url(self):
        return self.get_object().apiary.get_absolute_url()


class HiveFileView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/file_form.html'
    model = File
    fields = ['file']

    def get_success_url(self):
        return reverse('frontend:hive-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.hive = get_object_or_404(Hive, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class HiveFileDownloadView(LoginRequiredMixin, PrivateStorageDetailView):
    model = File
    model_file_field = 'file'
    content_disposition = True

    def get_queryset(self):
        return super().get_queryset().filter(hive__isnull=False, hive__owner=self.request.user)


class HiveFileDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/file_delete.html'
    model = File
    context_object_name = 'file'

    def get_queryset(self):
        return File.objects.filter(hive__apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.hive.get_absolute_url()


class QueenEditView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/hive/queen/form.html'
    model = Queen
    fields = ['year', 'number']

    def get_queryset(self):
        return Queen.objects.filter(hive__apiary__owner=self.request.user)

    def get_object(self, queryset=None):
        qs = self.get_queryset() if queryset is None else queryset
        return qs.get(hive__pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = self.get_object().hive

        return context


class QueenCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/hive/queen/form.html'
    model = Queen
    fields = ['year', 'number']

    def get_success_url(self):
        return reverse('frontend:hive-detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        form.instance.hive = get_object_or_404(Hive, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = get_object_or_404(Hive, pk=self.kwargs.get('pk'))

        return context


class QueenDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/hive/queen/delete.html'
    model = Queen
    context_object_name = 'queen'

    def get_queryset(self):
        return Queen.objects.filter(hive__apiary__owner=self.request.user)

    def get_object(self, queryset=None):
        qs = self.get_queryset() if queryset is None else queryset
        return qs.get(hive__pk=self.kwargs['pk'])

    def get_success_url(self):
        return self.object.hive.get_absolute_url()

beez/frontend/views/inspection.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from core.models import Inspection, Hive
from frontend.views import forms


class InspectionDetailView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/inspection/detail.html'
    model = Inspection
    context_object_name = 'inspection'

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)


class InspectionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'frontend/inspection/form.html'
    form_class = forms.InspectionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = get_object_or_404(Hive, pk=self.kwargs.get('pk'))

        return context

    def form_valid(self, form):
        form.instance.hive = Hive.objects.get(apiary__owner=self.request.user, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class InspectionUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'frontend/inspection/form.html'
    form_class = forms.InspectionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hive'] = self.get_object().hive

        return context

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)


class InspectionDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'frontend/inspection/delete.html'
    model = Inspection
    context_object_name = 'inspection'

    def get_queryset(self):
        return Inspection.objects.filter(hive__apiary__owner=self.request.user)

    def get_success_url(self):
        return self.object.hive.get_absolute_url()

beez/frontend/views/search.py
from django.shortcuts import render

from core.models import Apiary, Hive, Queen


def search(request):
    query = request.GET.get('q')

    apiaries = Apiary.search(query)
    hives = Hive.search(query)
    queens = Queen.search(query)

    return render(request, 'frontend/search.html', {
        'apiaries': apiaries,
        'hives': hives,
        'queens': queens,
    })

beez/frontend/views/settings.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

from core.models import Settings


class SettingsView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Settings
    template_name = 'frontend/settings.html'
    fields = ['weight_unit', 'temperature_unit', 'timezone', 'language']
    success_url = reverse_lazy('frontend:settings')
    success_message = _('Settings saved')

    def get_object(self, queryset=None):
        return self.request.user.settings

beez/frontend/views/statistics.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DetailView

from core.models import Apiary, Hive


class StatisticsView(LoginRequiredMixin, TemplateView):
    template_name = 'frontend/statistics/overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        apiaries = Apiary.objects.filter(owner=self.request.user)
        hives = Hive.objects.filter(apiary__owner=self.request.user)
        context['total_apiaries'] = apiaries.count()
        context['total_hives'] = hives.count()
        context['total_weight'] = sum(hive.last_recorded_weight or 0 for hive in hives)

        return context


class HiveStatisticsView(LoginRequiredMixin, DetailView):
    template_name = 'frontend/statistics/hive.html'
    context_object_name = 'hive'

    def get_queryset(self):
        return Hive.objects.filter(apiary__owner=self.request.user)

beez/frontend/views/user.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('frontend:apiary-list')

    def form_valid(self, form):
        response =  super().form_valid(form)
        user = self.object
        if user:
            login(self.request, user)
        return response

beez/frontend/templates/frontend/hive/delete.html
{% extends 'frontend/master.html' %}

{% load i18n %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">Delete Hive</h1>
            <div class="message is-danger">
                <p class="message-body">
                    {% trans 'Do you really want to delete this hive?' %}
                </p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="has-text-centered">
                    <a href="{% url 'frontend:hive-detail' pk=hive.pk %}" class="button">
                        {% trans 'Cancel' %}
                    </a>
                    <button class="button is-danger">
                        {% trans 'Delete Hive' %}
                    </button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

beez/frontend/templates/frontend/hive/detail.html
{% extends 'frontend/master.html' %}

{% load qr_code markdown_deux_tags colors i18n inspection %}

{% block title %}{{ hive.name }} - {{ block.super }}{% endblock %}

{% block head %}
    <style>
        .year-circle:before {
            content: '';
            display: inline-block;
            width: 1em;
            height: 1em;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            border-radius: 50%;
            background-color: grey;
        }

        .year-circle.blue:before {
            background-color: hsl(240, 80%, 50%);
        }

        .year-circle.white:before {
            background-color: hsl(0, 80%, 100%);
        }

        .year-circle.yellow:before {
            background-color: hsl(60, 80%, 50%);
        }

        .year-circle.red:before {
            background-color: hsl(0, 80%, 50%);
        }

        .year-circle.green:before {
            background-color: hsl(120, 80%, 50%);
        }
    </style>
{% endblock %}

{% block body %}
    <section class="section">
        <div class="container">
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{% url 'frontend:apiary-list' %}">{% trans 'Apiaries' %}</a></li>
                    <li><a href="{% url 'frontend:apiary-detail' pk=hive.apiary.pk %}">{{ hive.apiary.name }}</a></li>
                    <li class="is-active"><a href="{% url 'frontend:hive-detail' pk=hive.pk %}">{{ hive.name }}</a></li>
                </ul>
            </nav>

            <h1 class="title">
                <span>{{ hive.name }} {% if hive.makes_honey %} <span class="tag is-info is-medium"><i class="fa fa-dollar-sign"></i></span>{% endif %}</span>
                <a href="{% url 'frontend:hive-edit' pk=hive.pk %}">
                    <span class="icon"><i class="fa fa-pencil-alt"></i></span>
                </a>
            </h1>

            <div class="tabs is-centered">
                <ul>
                    <li class="is-active">
                        <a href="{% url 'frontend:hive-detail' pk=hive.pk %}">
                            <span class="icon"><i class="fa fa-archive"></i></span>
                            <span>{% trans 'Hive' %}</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'frontend:statistics-hive' pk=hive.pk %}">
                            <span class="icon"><i class="fa fa-chart-line"></i></span>
                            <span>{% trans 'Statistics' %}</span>
                        </a>
                    </li>
                </ul>
            </div>

            <h2 class="title is-4">{% trans 'Inspections' %}</h2>
            <table class="table is-striped is-fullwidth is-striped is-hoverable">
                <thead>
                <tr>
                    <th>{% trans 'Date' %}</th>
                    <th class="is-hidden-touch"><abbr title="{% trans 'Summary' %}">{% trans 'Smry' %}</abbr></th>
                    <th class="is-hidden-touch">{% trans 'Notes' %}</th>
                    <th class="is-hidden-touch"></th>
                </tr>
                </thead>
                <tbody>
                {% for inspection in hive.inspections.all %}
                    <tr>
                        <td><a href="{% url 'frontend:inspection-detail' pk=inspection.pk %}">{{ inspection.date }}</a></td>
                        <td class="is-hidden-touch">
                            {{ inspection|inspection_summary:user.settings.current_weight_unit }}
                        </td>
                        <td class="is-hidden-touch">
                            {% if inspection.notes %}
                                {{ inspection.notes|truncatechars:50 }}
                            {% else %}
                                <em>{% trans 'N/A' %}</em>
                            {% endif %}
                        </td>
                        <td class="has-text-right is-hidden-touch">
                            <a href="{% url 'frontend:inspection-edit' pk=inspection.pk %}" class="button is-small" title="Edit Inspection">
                                <span class="icon"><i class="fa fa-pencil-alt"></i></span>
                            </a>
                            <a href="{% url 'frontend:inspection-delete' pk=inspection.pk %}" class="button is-small is-danger" title="Delete Inspection">
                                <span class="icon"><i class="fa fa-trash-alt"></i></span>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">
                            <em>{% trans 'No Inspections' %}</em>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if hive.inspections.count > 0 %}
                <div class="buttons">
                    <a class="button is-success" href="{% url 'frontend:inspection-create' pk=hive.pk %}">
                        <span class="icon"><i class="fa fa-plus"></i></span>
                        <span>{% trans 'Add Inspection' %}</span>
                    </a>
                </div>
            {% else %}
                <div class="buttons is-centered">
                    <a href="{% url 'frontend:inspection-create' pk=hive.pk %}" class="button is-primary is-big">
                        <span class="icon"><i class="fa fa-plus"></i></span>
                        <span>{% trans 'Create Your First Inspection' %}</span>
                    </a>
                </div>
            {% endif %}

            <hr>

            <h2 class="title is-4">{% trans 'Details' %}</h2>
            <div class="columns is-multiline">
                <div class="column is-half">
                    <div class="box">
                        <h3 class="subtitle">{% trans 'Notes' %}</h3>
                        {% if hive.notes %}
                            <div class="content">{{ hive.notes|markdown }}</div>
                        {% else %}
                            <em>{% trans 'N/A' %}</em>
                        {% endif %}
                    </div>
                </div>
                <div class="column is-half">
                    <div class="box">
                        <div class="level">
                            <div class="level-left">
                                <h3 class="subtitle">{% trans 'Queen' %}</h3>
                            </div>
                            <div class="level-right">
                                {% if hive.queen %}
                                    <a class="button is-small" href="{% url 'frontend:hive-edit-queen' pk=hive.pk %}">
                                        <span class="icon">
                                            <i class="fa fa-edit"></i>
                                        </span>
                                    </a>
                                    <a class="button is-small" href="{% url 'frontend:hive-delete-queen' pk=hive.pk %}">
                                        <span class="icon">
                                            <i class="fa fa-trash"></i>
                                        </span>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        {% if hive.queen %}
                            <div class="content">
                                <dl>
                                    <dt>{% trans 'Year' %}</dt>
                                    <dd><span class="year-circle {{ hive.queen.year|year_color }}"></span> {{ hive.queen.year }}</dd>

                                    {% if hive.queen.number %}
                                        <dt>{% trans 'Number' %}</dt>
                                        <dd>{{ hive.queen.number }}</dd>
                                    {% endif %}
                                </dl>
                            </div>
                        {% else %}
                            <a href="{% url 'frontend:hive-add-queen' pk=hive.pk %}" class="button">{% trans 'Specify queen' %}</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <hr>

            <h2 class="title is-4">Files</h2>
            <table class="table is-fullwidth is-striped">
                <tr>
                    <th>{% trans 'File' %}</th>
                    <th>{% trans 'Uploaded' %}</th>
                    <th class="is-hidden-touch">{% trans 'Size' %}</th>
                    <th></th>
                </tr>
                {% for file in hive.files.all %}
                    <tr>
                        <td>
                            <a href="{% url 'frontend:hive-file' pk=file.pk %}" target="_blank">
                                {{ file.file.name }} <span class="icon"><i class="fa fa-download"></i></span>
                            </a>
                        </td>
                        <td>
                            {{ file.date_created }}
                        </td>
                        <td class="is-hidden-touch">
                            {{ file.file.size|filesizeformat }}
                        </td>
                        <td>
                            <a href="{% url 'frontend:hive-file-delete' pk=file.pk %}" class="button is-danger is-small" title="Delete file">
                                <span class="icon">
                                    <i class="fa fa-trash"></i>
                                </span>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">
                            <em>{% trans 'No files yet.' %}</em>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% if hive.files.count > 0 %}
                <div class="buttons">
                    <a class="button is-success" href="{% url 'frontend:hive-add-file' pk=hive.pk %}">
                        <span class="icon"><i class="fa fa-plus"></i></span>
                        <span>{% trans 'Add File' %}</span>
                    </a>
                </div>
            {% else %}
                <div class="buttons is-centered">
                    <a href="{% url 'frontend:hive-add-file' pk=hive.pk %}" class="button is-primary is-big">
                        <span class="icon"><i class="fa fa-plus"></i></span>
                        <span>{% trans 'Add Your First File' %}</span>
                    </a>
                </div>
            {% endif %}

            <hr>

            <div class="buttons">
                <a href="{% url 'frontend:hive-transfer' pk=hive.pk %}" class="button">
                    <span class="icon"><i class="fa fa-exchange-alt"></i></span>
                    <span>{% trans 'Transfer Hive' %}</span>
                </a>
                <a href="{% url 'frontend:hive-delete' pk=hive.pk %}" class="button is-danger">
                    <span class="icon"><i class="fa fa-ban"></i></span>
                    <span>{% trans 'Delete Hive' %}</span>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

beez/frontend/templates/frontend/hive/file_delete.html
{% extends 'frontend/master.html' %}

{% load i18n %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">Delete File</h1>
            <div class="message is-danger">
                <p class="message-body">
                    {% blocktrans %}Do you really want to delete the file <strong>{{ file.file.name }}</strong>?{% endblocktrans %}
                </p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="has-text-centered">
                    <a href="{% url 'frontend:hive-detail' pk=file.hive.pk %}" class="button">
                        {% trans 'Cancel' %}
                    </a>
                    <button class="button is-danger">
                        {% trans 'Delete File' %}
                    </button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

beez/frontend/templates/frontend/hive/file_form.html
{% extends 'frontend/apiary/file_form.html' %}

{% block title %}
    Add file to hive
{% endblock %}